GET http://localhost:8080/
###
GET http://localhost:8080/dsNguoidung
###
GET http://localhost:8080/dsTivi
###
POST http://localhost:8080/ThemNguoidung
Content-Type: application/json

{
        "Ho_ten": "Nguyễn Anh Tuấn",
        "Ma_so": "QL_100",
        "Ten_Dang_nhap": "natuan",
        "Mat_khau": "123456",
        "Nhom_Nguoi_dung": {
            "Ten": "Nhân viên Quản lý",
            "Ma_so": "NHAN_VIEN_QUAN_LY"
        }
    }
###
POST http://localhost:8080/SuaNguoidung 
Content-Type: application/json

{
    "Ma_so":"QL_100",
    "Ho_ten": "Nguyễn Anh Tuấn Tài"
}
###
POST http://localhost:8080/XoaNguoidung 
Content-Type: application/json

{
    "Ma_so":"QL_100"
}
###
GET http://localhost:8080/TIVI_1.png